<?php

namespace App\Support\Predictive;

use App\Models\FailureMode;

/**
 * Taxonomía de referencia de modos de falla.
 *
 * Los patrones de texto salen de las bitácoras reales analizadas en el cambio 046: el mismo modo
 * aparece escrito de muchas formas (`reparacion de eje`, `reparación de equipo, eje dañado`,
 * `reparacio de eje`), por lo que la normalización se hace por subcadena sobre texto sin acentos.
 *
 * `equipment_classes` vacío significa aplicable a cualquier clase.
 */
final class FailureModeCatalog
{
    public const CLASS_MOBILE = ['JUMBO', 'SCOOPTRAM', 'CAMION_BAJO_PERFIL'];

    public const CLASS_PLANT = [
        'QUEBRADORA', 'MOLINO', 'CRIBA', 'CELDA_FLOTACION', 'ESPESADOR', 'FILTRO',
        'BANDA_TRANSPORTADORA', 'ALIMENTADOR', 'BOMBA', 'ELEVADOR', 'ACONDICIONADOR',
    ];

    /**
     * @return list<array<string, mixed>>
     */
    public static function definitions(): array
    {
        return [
            // ------------------------------------------------------------------ tren motriz
            [
                'code' => 'EJE_TREN_MOTRIZ',
                'name' => 'Eje o flecha del tren motriz',
                'system' => 'tren_motriz',
                'severity' => 'critical',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Vibración y ruido al desplazarse, juego axial, fuga por retenes del eje.',
                'typical_causes' => 'Fatiga por sobrecarga, falta de lubricación, impacto contra tope de rampa.',
                'monitoring_signals' => ['vibracion', 'analisis_aceite', 'inspeccion_visual'],
                'mean_repair_hours' => 12.0,
                'text_patterns' => [
                    'eje danado', 'eje oscilante', 'reparacion de eje', 'reparacion eje', 'reparacio de eje',
                    'de equipo, eje', 'de equipo eje', 'ejes', 'instalacion de flechas', 'flecha',
                ],
            ],
            [
                'code' => 'TREN_MOTRIZ',
                'name' => 'Tren motriz (diferencial y mandos finales)',
                'system' => 'tren_motriz',
                'severity' => 'critical',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Pérdida de tracción, ruido metálico bajo carga, temperatura alta en mandos.',
                'typical_causes' => 'Desgaste de engranes, aceite degradado, contaminación por agua.',
                'monitoring_signals' => ['analisis_aceite', 'termografia', 'vibracion'],
                'mean_repair_hours' => 24.0,
                'text_patterns' => ['tren motriz', 'mando final', 'diferencial'],
            ],
            [
                'code' => 'CAJA_TRANSFERENCIA',
                'name' => 'Caja de transferencia',
                'system' => 'tren_motriz',
                'severity' => 'high',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Fuga de aceite, ruido al cambiar de rango, soldadura agrietada en carcasa.',
                'typical_causes' => 'Fatiga estructural, montaje flojo, sobrecarga.',
                'monitoring_signals' => ['analisis_aceite', 'inspeccion_visual'],
                'mean_repair_hours' => 16.0,
                'text_patterns' => [
                    'caja de transferencia', 'caja de trasnferencia', 'caja de trans', 'soldadura caja',
                    'caja metalera',
                ],
            ],
            [
                'code' => 'CONVERTIDOR_PAR',
                'name' => 'Convertidor de par',
                'system' => 'transmision',
                'severity' => 'high',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Falta de fuerza, sobrecalentamiento de transmisión, fuga de aceite.',
                'typical_causes' => 'Desgaste interno, aceite fuera de especificación, enfriador obstruido.',
                'monitoring_signals' => ['analisis_aceite', 'termografia'],
                'mean_repair_hours' => 18.0,
                'text_patterns' => ['convertidor', 'fuga de convertidor'],
            ],
            [
                'code' => 'TRANSMISION',
                'name' => 'Transmisión',
                'system' => 'transmision',
                'severity' => 'critical',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Cambios bruscos o no engrana, presión de línea baja.',
                'typical_causes' => 'Desgaste de discos, solenoide dañado, aceite contaminado.',
                'monitoring_signals' => ['analisis_aceite', 'presion_hidraulica'],
                'mean_repair_hours' => 24.0,
                'text_patterns' => ['transmision', 'no engrana', 'cambios'],
            ],
            [
                'code' => 'YUGO_CARDAN',
                'name' => 'Yugo o cardán',
                'system' => 'tren_motriz',
                'severity' => 'high',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Vibración a velocidad, golpeteo al arrancar.',
                'typical_causes' => 'Crucetas sin grasa, desbalance, tornillería floja.',
                'monitoring_signals' => ['vibracion', 'inspeccion_visual'],
                'mean_repair_hours' => 8.0,
                'text_patterns' => ['yugo', 'cardan', 'cruceta'],
            ],
            [
                'code' => 'CHUMACERA',
                'name' => 'Chumacera o rodamiento',
                'system' => 'mecanico',
                'severity' => 'high',
                'equipment_classes' => [],
                'typical_symptoms' => 'Ruido agudo, temperatura elevada, vibración creciente.',
                'typical_causes' => 'Falta de lubricación, contaminación, desalineación.',
                'monitoring_signals' => ['vibracion', 'termografia', 'analisis_aceite'],
                'mean_repair_hours' => 10.0,
                'text_patterns' => ['chumacera', 'rodamiento', 'balero'],
            ],
            [
                'code' => 'BUJE_PASADOR',
                'name' => 'Buje o pasador',
                'system' => 'mecanico',
                'severity' => 'medium',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Juego en articulaciones, golpeteo del brazo o cucharón.',
                'typical_causes' => 'Engrase deficiente, desgaste normal, sobrecarga.',
                'monitoring_signals' => ['inspeccion_visual'],
                'mean_repair_hours' => 6.0,
                'text_patterns' => ['buje', 'pasador'],
            ],

            // ------------------------------------------------------------------ hidráulico
            [
                'code' => 'CILINDRO_HIDRAULICO',
                'name' => 'Cilindro hidráulico (levante y volteo)',
                'system' => 'hidraulico',
                'severity' => 'high',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Cae la carga, fuga por vástago, movimiento lento.',
                'typical_causes' => 'Sellos vencidos, vástago rayado, presión excesiva.',
                'monitoring_signals' => ['presion_hidraulica', 'inspeccion_visual', 'consumo_aceite'],
                'mean_repair_hours' => 10.0,
                'text_patterns' => [
                    'cilindro de levante', 'cil levante', 'cilindro levante', 'reparcion cil',
                    'reparacion de cil', 'cilindro',
                ],
            ],
            [
                'code' => 'FUGA_HIDRAULICA',
                'name' => 'Fuga hidráulica (mangueras y conexiones)',
                'system' => 'hidraulico',
                'severity' => 'medium',
                'equipment_classes' => [],
                'typical_symptoms' => 'Consumo de aceite por encima de lo normal, charco bajo el equipo.',
                'typical_causes' => 'Manguera rozada o vencida, abrazadera floja, vibración.',
                'monitoring_signals' => ['consumo_aceite', 'inspeccion_visual'],
                'mean_repair_hours' => 4.0,
                'text_patterns' => [
                    'manguera danada', 'manguera rota', 'fuga de aceite', 'fuga hidraulica', 'manguera',
                ],
            ],
            [
                'code' => 'FILTRO_HIDRAULICO',
                'name' => 'Filtro hidráulico obstruido',
                'system' => 'hidraulico',
                'severity' => 'medium',
                'equipment_classes' => [],
                'typical_symptoms' => 'Alarma de filtro obstruido, respuesta lenta de actuadores.',
                'typical_causes' => 'Aceite contaminado, filtro fuera de intervalo, desgaste interno de bomba.',
                'monitoring_signals' => ['alarma_plc', 'analisis_aceite', 'presion_hidraulica'],
                'precursor_event_codes' => ['W651'],
                'mean_repair_hours' => 3.0,
                'text_patterns' => ['filtro de aceite hidraulico', 'filtro hidraulico obstruido'],
            ],
            [
                'code' => 'BOMBA_HIDRAULICA',
                'name' => 'Bomba hidráulica',
                'system' => 'hidraulico',
                'severity' => 'high',
                'equipment_classes' => [],
                'typical_symptoms' => 'Presión baja, ruido de cavitación, temperatura de aceite alta.',
                'typical_causes' => 'Desgaste por contaminación, succión restringida, aceite incorrecto.',
                'monitoring_signals' => ['presion_hidraulica', 'analisis_aceite', 'vibracion'],
                'precursor_event_codes' => ['M490'],
                'mean_repair_hours' => 12.0,
                'text_patterns' => ['bomba hidraulica', 'presion hidraulica'],
            ],
            [
                'code' => 'SISTEMA_LUBRICACION',
                'name' => 'Sistema de lubricación',
                'system' => 'lubricacion',
                'severity' => 'critical',
                'equipment_classes' => [],
                'typical_symptoms' => 'Nivel bajo de aceite, filtro de lubricación obstruido, paro por baja presión.',
                'typical_causes' => 'Fuga, bomba de lubricación desgastada, filtro fuera de intervalo.',
                'monitoring_signals' => ['alarma_plc', 'consumo_aceite', 'analisis_aceite'],
                'precursor_event_codes' => ['W351', 'A308', 'M302'],
                'mean_repair_hours' => 8.0,
                'text_patterns' => [
                    'sistema de lubricacion', 'falla en sistema de lubricacion', 'lubricacion',
                    'nivel del aceite lubricacion', 'filtro de aceite lubricacion',
                ],
            ],

            // ------------------------------------------------------------------ motor y eléctrico
            [
                'code' => 'MOTOR_DIESEL',
                'name' => 'Motor diésel',
                'system' => 'motor_diesel',
                'severity' => 'critical',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Pérdida de potencia, humo anormal, consumo de aceite alto, sobrecalentamiento.',
                'typical_causes' => 'Desgaste de anillos, inyección deficiente, enfriamiento obstruido.',
                'monitoring_signals' => ['consumo_aceite', 'consumo_diesel', 'analisis_aceite', 'termografia'],
                'mean_repair_hours' => 32.0,
                'text_patterns' => ['reparacion de motor', 'motor danado', 'falla de motor', 'sobrecalentamiento'],
            ],
            [
                'code' => 'SISTEMA_ENFRIAMIENTO',
                'name' => 'Sistema de enfriamiento',
                'system' => 'motor_diesel',
                'severity' => 'high',
                'equipment_classes' => [],
                'typical_symptoms' => 'Temperatura alta, consumo de refrigerante, enfriador ciclando.',
                'typical_causes' => 'Panal obstruido, termostato, fuga de refrigerante, cooler detenido.',
                'monitoring_signals' => ['consumo_refrigerante', 'termografia', 'alarma_plc'],
                // Metso IC70C: M331/M332 = Cooler running/stopped (enfriador), no radiador.
                'precursor_event_codes' => ['M331', 'M332', 'M334', 'M335'],
                'mean_repair_hours' => 6.0,
                'text_patterns' => ['radiador', 'refrigerante', 'enfriamiento', 'enfriador', 'cooler', 'temperatura alta'],
            ],
            [
                'code' => 'SISTEMA_ELECTRICO',
                'name' => 'Sistema eléctrico y de arranque',
                'system' => 'electrico',
                'severity' => 'high',
                'equipment_classes' => [],
                'typical_symptoms' => 'No arranca, fases invertidas, contactor no retorna, falla intermitente.',
                'typical_causes' => 'Conexión floja, alternador o batería, humedad, contactor desgastado.',
                'monitoring_signals' => ['alarma_plc', 'termografia', 'inspeccion_visual'],
                'precursor_event_codes' => ['A401', 'A402', 'A102', 'A105'],
                'mean_repair_hours' => 6.0,
                'text_patterns' => [
                    'falla electrica', 'faces invertidas', 'fases invertidas', 'falla de encendido',
                    'no enciende', 'falla de arranque', 'contactor',
                ],
            ],
            [
                'code' => 'SOBRECARGA_MOTOR',
                'name' => 'Sobrecarga del motor eléctrico',
                'system' => 'electrico',
                'severity' => 'high',
                'equipment_classes' => self::CLASS_PLANT,
                'typical_symptoms' => 'Disparo por sobrecorriente, potencia por encima del nominal.',
                'typical_causes' => 'Alimentación excesiva, material atorado, desgaste de corazas.',
                'monitoring_signals' => ['alarma_plc', 'potencia_motor'],
                'precursor_event_codes' => ['A403', 'W451', 'W461', 'A404'],
                'mean_repair_hours' => 5.0,
                'text_patterns' => ['sobrecarga', 'sobre carga', 'potencia demasiada', 'maxima potencia'],
            ],
            [
                'code' => 'SENSOR_INSTRUMENTACION',
                'name' => 'Sensor o instrumentación de control',
                'system' => 'instrumentacion',
                'severity' => 'medium',
                'equipment_classes' => [],
                'typical_symptoms' => 'Lectura errática, falla de rotación reportada sin causa mecánica.',
                'typical_causes' => 'Sensor sucio o desalineado, cableado, módulo de medición faltante.',
                'monitoring_signals' => ['alarma_plc'],
                'precursor_event_codes' => ['A408', 'A440', 'A441', 'A126'],
                'mean_repair_hours' => 3.0,
                'text_patterns' => ['sensor', 'sensor de dientes', 'falla de rotacion', 'modulo medicion'],
            ],

            // ------------------------------------------------------------------ estructura y desgaste
            [
                'code' => 'ESTRUCTURA_CUCHARON',
                'name' => 'Estructura, cucharón o caja',
                'system' => 'estructural',
                'severity' => 'high',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Grietas, soldadura abierta, daño frontal por impacto.',
                'typical_causes' => 'Impacto, fatiga, carga descentrada.',
                'monitoring_signals' => ['inspeccion_visual'],
                'mean_repair_hours' => 14.0,
                'text_patterns' => [
                    'cucharon', 'soldadura de cucharon', 'dano frontal', 'soldadura', 'estructura',
                    'descrucerado',
                ],
            ],
            [
                'code' => 'LLANTAS',
                'name' => 'Llantas y rines',
                'system' => 'rodamiento',
                'severity' => 'medium',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Ponchadura, desgaste irregular, corte de banda.',
                'typical_causes' => 'Piso con roca suelta, presión incorrecta, sobrecarga.',
                'monitoring_signals' => ['inspeccion_visual'],
                'mean_repair_hours' => 4.0,
                'text_patterns' => ['llanta', 'ponchado', 'ponchador', 'rin'],
            ],
            [
                'code' => 'LAINAS_DESGASTE',
                'name' => 'Lainas y elementos de desgaste',
                'system' => 'desgaste',
                'severity' => 'high',
                'equipment_classes' => self::CLASS_PLANT,
                'typical_symptoms' => 'Desgaste al 100 %, ajuste automático deshabilitado, granulometría fuera.',
                'typical_causes' => 'Vida útil consumida, material abrasivo, alimentación descentrada.',
                'monitoring_signals' => ['alarma_plc', 'inspeccion_visual', 'horometro'],
                'precursor_event_codes' => ['W459', 'M488'],
                'mean_repair_hours' => 20.0,
                'text_patterns' => ['lainas', 'laina', 'coraza', 'desgaste', 'blindaje'],
            ],
            [
                'code' => 'FALDON',
                'name' => 'Faldón de transferencia',
                'system' => 'desgaste',
                'severity' => 'low',
                'equipment_classes' => self::CLASS_PLANT,
                'typical_symptoms' => 'Derrame de material en punto de transferencia, faldón caído.',
                'typical_causes' => 'Desgaste del hule, sujeción floja.',
                'monitoring_signals' => ['inspeccion_visual'],
                'mean_repair_hours' => 3.0,
                'text_patterns' => ['faldon'],
            ],
            [
                'code' => 'EMBRAGUE',
                'name' => 'Embrague',
                'system' => 'transmision',
                'severity' => 'high',
                'equipment_classes' => self::CLASS_PLANT,
                'typical_symptoms' => 'El equipo se embraga o desembraga solo, patinamiento.',
                'typical_causes' => 'Desgaste de forros, presión de aire baja, falta de carga sostenida.',
                'monitoring_signals' => ['inspeccion_visual', 'presion_aire'],
                'mean_repair_hours' => 16.0,
                'text_patterns' => ['embrague', 'se embraga', 'desambrague', 'desembrague'],
            ],
            [
                'code' => 'BANDA_TRANSPORTADORA',
                'name' => 'Banda transportadora',
                'system' => 'transporte',
                'severity' => 'medium',
                'equipment_classes' => self::CLASS_PLANT,
                'typical_symptoms' => 'Desalineación, banda dañada, paro por sobrecarga.',
                'typical_causes' => 'Empalme vencido, polea desalineada, carga fuera de centro.',
                'monitoring_signals' => ['inspeccion_visual', 'alarma_plc'],
                'precursor_event_codes' => ['M522'],
                'mean_repair_hours' => 8.0,
                'text_patterns' => [
                    'banda danada', 'desalineacion banda', 'banda 0', 'banda 1', 'banda 7', 'problema en banda',
                    'sobrecarga b2', 'cinta transportadora',
                ],
            ],
            [
                'code' => 'CRIBA_VIBRATORIA',
                'name' => 'Criba vibratoria',
                'system' => 'clasificacion',
                'severity' => 'medium',
                'equipment_classes' => ['CRIBA'],
                'typical_symptoms' => 'Sonido anormal, malla rota, vibración fuera de patrón.',
                'typical_causes' => 'Rodamiento del excitador, malla vencida, resortes.',
                'monitoring_signals' => ['vibracion', 'inspeccion_visual'],
                'mean_repair_hours' => 10.0,
                'text_patterns' => ['criba', 'sonido anormal criba', 'malla'],
            ],
            [
                'code' => 'OBSTRUCCION_ALIMENTACION',
                'name' => 'Obstrucción de alimentación',
                'system' => 'proceso',
                'severity' => 'medium',
                'equipment_classes' => self::CLASS_PLANT,
                'typical_symptoms' => 'Piedra atorada, línea obstruida, alimentador parado por pausa máxima.',
                'typical_causes' => 'Granulometría fuera de rango, material húmedo, chute mal diseñado.',
                'monitoring_signals' => ['alarma_plc'],
                'precursor_event_codes' => ['M502', 'M504'],
                'mean_repair_hours' => 2.0,
                'text_patterns' => [
                    'piedra atorada', 'linea de alimentacion obstruida', 'obstruida', 'atorada', 'alimentador parado',
                ],
            ],
            [
                'code' => 'COMPRESOR',
                'name' => 'Compresor de aire',
                'system' => 'aire',
                'severity' => 'high',
                'equipment_classes' => [],
                'typical_symptoms' => 'Presión de aire baja, paro por falla de compresor.',
                'typical_causes' => 'Filtro saturado, válvula, motor.',
                'monitoring_signals' => ['presion_aire', 'termografia'],
                'mean_repair_hours' => 8.0,
                'text_patterns' => ['compresor', 'falla de compresor', 'presion de aire'],
            ],
            [
                'code' => 'PERFORADORA_PERCUSION',
                'name' => 'Perforadora: percusión y rotación',
                'system' => 'perforacion',
                'severity' => 'high',
                'equipment_classes' => ['JUMBO'],
                'typical_symptoms' => 'Velocidad de penetración baja, barrenos fuera de especificación, fuga en martillo.',
                'typical_causes' => 'Pistón desgastado, acumulador descargado, agua de barrido insuficiente.',
                'monitoring_signals' => ['presion_hidraulica', 'horometro', 'inspeccion_visual'],
                'mean_repair_hours' => 10.0,
                'text_patterns' => ['percusion', 'rotacion', 'martillo', 'barra', 'perforadora', 'brazo'],
            ],
            [
                'code' => 'FRENOS',
                'name' => 'Sistema de frenos',
                'system' => 'frenos',
                'severity' => 'critical',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Prueba de frenado fuera de norma, presión de acumuladores baja.',
                'typical_causes' => 'Discos desgastados, sellos, acumulador sin carga.',
                'monitoring_signals' => ['prueba_frenos', 'presion_hidraulica'],
                'mean_repair_hours' => 8.0,
                'text_patterns' => ['freno', 'frenos', 'frenado'],
            ],
            [
                'code' => 'DIRECCION',
                'name' => 'Sistema de dirección',
                'system' => 'hidraulico',
                'severity' => 'critical',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Dirección dura o con juego, no responde en articulación.',
                'typical_causes' => 'Orbitrol, cilindro de dirección, presión insuficiente.',
                'monitoring_signals' => ['presion_hidraulica', 'inspeccion_visual'],
                'mean_repair_hours' => 8.0,
                'text_patterns' => ['direccion', 'falla en la direccion', 'orbitrol'],
            ],
            [
                'code' => 'SELLOS_EMPAQUES',
                'name' => 'Sellos y empaques',
                'system' => 'mecanico',
                'severity' => 'low',
                'equipment_classes' => [],
                'typical_symptoms' => 'Goteo, humedad en juntas, pérdida de nivel lenta.',
                'typical_causes' => 'Envejecimiento del elastómero, sobrepresión, montaje.',
                'monitoring_signals' => ['inspeccion_visual', 'consumo_aceite'],
                'mean_repair_hours' => 4.0,
                'text_patterns' => ['empaque', 'empaques', 'sello', 'reten', 'estopero'],
            ],
            [
                'code' => 'SUPRESION_INCENDIO',
                'name' => 'Supresión de incendio (Ansul)',
                'system' => 'seguridad',
                'severity' => 'critical',
                'equipment_classes' => self::CLASS_MOBILE,
                'typical_symptoms' => 'Sistema descargado o sin presión; el equipo queda fuera por seguridad.',
                'typical_causes' => 'Descarga accidental, falta de recarga programada, manguera dañada.',
                'monitoring_signals' => ['inspeccion_visual', 'checklist_preoperacional'],
                'mean_repair_hours' => 4.0,
                'text_patterns' => ['ansul', 'ansol', 'supresion de incendio', 'extincion'],
            ],
            [
                'code' => 'PARO_EMERGENCIA',
                'name' => 'Paro de emergencia',
                'system' => 'seguridad',
                'severity' => 'medium',
                'equipment_classes' => [],
                'typical_symptoms' => 'Activación de botón de paro, corte de secuencia.',
                'typical_causes' => 'Intervención del operador, enclavamiento, falla de seguridad.',
                'monitoring_signals' => ['alarma_plc'],
                'precursor_event_codes' => ['A101'],
                'mean_repair_hours' => 1.0,
                'text_patterns' => ['paro de emergencia', 'parada de emergencia'],
            ],

            // ------------------------------------------------------------------ no es falla de equipo
            [
                'code' => 'SERVICIO_PROGRAMADO',
                'name' => 'Servicio programado',
                'system' => 'preventivo',
                'severity' => 'low',
                'equipment_classes' => [],
                'typical_symptoms' => 'Intervención planeada por horas de operación.',
                'typical_causes' => 'Plan de mantenimiento por intervalo.',
                'monitoring_signals' => ['horometro'],
                'mean_repair_hours' => 6.0,
                'text_patterns' => [
                    'mantenimiento general', 'mantenimiento preventivo', 'paro preventivo', 'servicio',
                    'rutina semanal', 'aplicacion de rutina', 'inspeccion', 'cambio de aceite',
                    'cambio de filtros', 'servicio 1000 horas', 'servicio 500', 'servicio 250',
                ],
            ],
            [
                'code' => 'PARO_OPERATIVO',
                'name' => 'Paro operativo (sin falla de equipo)',
                'system' => 'operacion',
                'severity' => 'low',
                'equipment_classes' => [],
                'typical_symptoms' => 'Equipo disponible sin producir: falta de carga, acarreo lento, bajo sólido.',
                'typical_causes' => 'Cuello de botella del proceso, amacice, disponibilidad de frente.',
                'monitoring_signals' => ['utilizacion'],
                'mean_repair_hours' => 0.0,
                'text_patterns' => [
                    'falta de carga', 'sin carga', 'bajo solido', 'acarreo lento', 'falta de acarreo',
                    'amacice', 'paro por falta', 'sin frente', 'espera',
                ],
            ],
            [
                'code' => 'SIN_OPERADOR',
                'name' => 'Sin operador',
                'system' => 'operacion',
                'severity' => 'low',
                'equipment_classes' => [],
                'typical_symptoms' => 'Equipo disponible sin asignación de operador en el turno.',
                'typical_causes' => 'Plantilla incompleta, ausentismo, reasignación.',
                'monitoring_signals' => ['utilizacion'],
                'mean_repair_hours' => 0.0,
                'text_patterns' => ['no operador', 'sin operador', 'falta operador', 'falta de operador'],
            ],
            [
                'code' => 'SIN_FALLA',
                'name' => 'Trabajo normal',
                'system' => 'operacion',
                'severity' => 'low',
                'equipment_classes' => [],
                'typical_symptoms' => 'Turno sin novedades.',
                'typical_causes' => null,
                'monitoring_signals' => [],
                'mean_repair_hours' => 0.0,
                'text_patterns' => [
                    'trabajo normal', 'trabajo nromal', 'trabajonormal', 'sin comentarios', 'normal',
                    'todo bien', 'si operador',
                ],
            ],
            [
                'code' => 'OTRA_FALLA',
                'name' => 'Otra falla no clasificada',
                'system' => 'indeterminado',
                'severity' => 'medium',
                'equipment_classes' => [],
                'typical_symptoms' => 'Reporte de falla sin coincidencia en la taxonomía.',
                'typical_causes' => null,
                'monitoring_signals' => [],
                'mean_repair_hours' => 6.0,
                'text_patterns' => [],
            ],
        ];
    }

    /** Modo al que se asignan las fallas cuyo texto no coincide con ningún patrón. */
    public const FALLBACK_CODE = 'OTRA_FALLA';

    /** Códigos que no representan una falla real del equipo. */
    public const NON_FAILURE_CODES = ['SIN_FALLA', 'SIN_OPERADOR', 'PARO_OPERATIVO', 'SERVICIO_PROGRAMADO'];

    /**
     * Siembra o actualiza la taxonomía de una empresa. Idempotente por `code`.
     *
     * @return array<string, int> Mapa de código a id.
     */
    public static function syncForCompany(int $companyId): array
    {
        $map = [];
        foreach (self::definitions() as $index => $definition) {
            $mode = FailureMode::withoutGlobalScope('company')->updateOrCreate(
                ['company_id' => $companyId, 'code' => $definition['code']],
                [
                    'name' => $definition['name'],
                    'system' => $definition['system'],
                    'severity' => $definition['severity'],
                    'equipment_classes' => $definition['equipment_classes'],
                    'typical_symptoms' => $definition['typical_symptoms'] ?? null,
                    'typical_causes' => $definition['typical_causes'] ?? null,
                    'monitoring_signals' => $definition['monitoring_signals'] ?? [],
                    'precursor_event_codes' => $definition['precursor_event_codes'] ?? [],
                    'mean_repair_hours' => $definition['mean_repair_hours'] ?? null,
                    'text_patterns' => $definition['text_patterns'] ?? [],
                    'sort_order' => $index * 10,
                ],
            );
            $map[$definition['code']] = (int) $mode->id;
        }

        return $map;
    }
}
